use_frameworks!

platform :ios, '9.0'

target 'ZCReLogger_Example' do
  pod 'ZCReLogger', :path => '../'

  target 'ZCReLogger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
